on:
  push:
    branches: [master]

jobs:
  sync-workouts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      # Add your workout syncing logic here
      
      - name: Commit changes to GitHub
        run: |
          git config --global user.email "whrss9527@gmail.com"
          git config --global user.name "whrss"
          git add .
          git commit -m "Add new workouts"
          git push origin master
